
logging:
  level:
    ROOT: INFO
    tech: INFO
    com.zkuzniar.workoutplanner: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${workoutPlanner.registry.password}@localhost:8761/eureka/

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 100
      uri: http://admin:${workoutPlanner.registry.password}@localhost:8761/config
      name: WorkoutPlanner
      profile: prod
      label: main
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/WorkoutPlanner
    username: WorkoutPlanner
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: tech.domain.util.FixedPostgreSQL10Dialect
  liquibase:
    contexts: prod
  thymeleaf:
    cache: true
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 8081
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

workoutPlanner:
  http:
    cache:
      timeToLiveInDays: 1461
  registry:
    password: admin
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
