logging:
  level:
    ROOT: DEBUG
    tech: DEBUG
    org.hibernate.SQL: DEBUG
    com.zkuzniar.workoutplanner: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${workoutPlanner.registry.password}@localhost:8761/eureka/

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  cloud:
    config:
      uri: http://admin:${workoutPlanner.registry.password}@localhost:8761/config
      name: WorkoutPlanner
      profile: dev
      label: main

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/WorkoutPlanner
    username: WorkoutPlanner
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: tech.workoutPlanner.domain.util.FixedPostgreSQL10Dialect
  liquibase:
    contexts: dev, faker
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 8081

workoutPlanner:
  registry:
    password: admin
  # cors:
  #   allowed-origins: "*"
  #   allowed-methods: "*"
  #   allowed-headers: "*"
  #   exposed-headers: "Authorization,Link,X-Total-Count"
  #   allow-credentials: true
  #   max-age: 1800
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

